inherits: ..\\languages-family-formats.yml

dimensions:
- alias: product
  values: [java]
- alias:  operation
  values: [remove]
- alias:  fileformat
  values: [excel, word, presentation, slides]

generationRules:
  include:
  - fileformat[excel, word, presentation, slides]
  
outputPath: "watermark\\{product}\\clear\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json]

