inherits: ..\\languages-family-formats.yml

dimensions:
- alias: product
  values: [nodejs-java]
- alias:  operation
  values: [edit]
- alias:  url
  values: [update]
- alias:  fileformat
  values: [excel, word, powerpoint]

generationRules:
  include:
  - fileformat[excel, word, powerpoint]
  
outputPath: "watermark\\{product}\\{url}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
