inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [edit]
- alias:  fileformat
  values: [doc, docx, jpeg, jpg, pdf, png, ppt, pptx, rtf, tif, tiff, webp, xls, xlsx]

generationRules:
  include:
  - fileformat[doc, docx, jpeg, jpg, pdf, png, ppt, pptx, rtf, tif, tiff, webp, xls, xlsx]
  
outputPath: "watermark\\{product}\\remake\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
