inherits: ..\\products_java.yml

dimensions:  
- alias:  operation
  values: [add] 
- alias:  fileformat
  values: [excel, word, images, photo, presentation, slides]

generationRules:
  include:
  - fileformat[excel, word, images, photo, presentation, slides]
  
outputPath: "watermark\\{product}\\generate\\{fileformat}.{lang}.md"
