inherits: ..\\products_java.yml

dimensions:  
- alias:  operation
  values: [add] 
- alias:  watermarktype
  values: [text]
- alias:  fileformat
  values: [bmp, doc, docm, docx, dot, dotm, dotx, excel, gif, image, jp2, jpeg, jpg, odt, pdf, png, pot, potm, potx, pps, ppsm, ppsx, ppt, pptm, pptx, presentation, rtf, spreadsheet, sxc, tif, tiff, txt, vdw, vdx, visio, vsd, vsdm, vsdx, vss, vssm, vssx, vst, vstm, vstx, vsx, vtx, webp, word, worksheet, xlam, xls, xlsb, xlsm, xlsx, xlt, xltm, xltx ]

dictionaries: ["..\\..\\data\\otherformats.json"]

generationRules:
  include:
  - watermarktype[text] + fileformat[bmp, doc, docm, docx, dot, dotm, dotx, excel, gif, image, jp2, jpeg, jpg, odt, pdf, png, pot, potm, potx, pps, ppsm, ppsx, ppt, pptm, pptx, presentation, rtf, spreadsheet, sxc, tif, tiff, txt, vdw, vdx, visio, vsd, vsdm, vsdx, vss, vssm, vssx, vst, vstm, vstx, vsx, vtx, webp, word, worksheet, xlam, xls, xlsb, xlsm, xlsx, xlt, xltm, xltx]
  
outputPath: "watermark\\{product}\\{operation}\\{watermarktype}\\{fileformat}.{lang}.md"
