inherits: ..\\languages-family-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [add]
- alias:  url
  values: [generate]
- alias:  fileformat
  values: [excel, word, image, photo, powerpoint]

generationRules:
  include:
  - fileformat[excel, word, image, photo, powerpoint]
  
outputPath: "watermark\\{product}\\{url}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
