inherits: ..\\products_net.yml

dimensions:  
- alias:  operation
  values: [search] 
- alias:  watermarktype
  values: [text]
- alias:  fileformat
  values: [doc, docm, docx, dot, dotm, dotx, excel, odt, pdf, pot, potm, potx, pps, ppsm, ppsx, ppt, pptm, pptx, presentation, rtf, spreadsheet, sxc, txt, vdw, vdx, visio, vsd, vsdm, vsdx, vss, vssm, vssx, vst, vstm, vstx, vsx, vtx, word, worksheet, xlam, xls, xlsb, xlsm, xlsx, xlt, xltm, xltx]

dictionaries: ["..\\..\\data\\otherformats.json"]

generationRules:
  include:
  - watermarktype[text] + fileformat[doc, docm, docx, dot, dotm, dotx, excel, odt, pdf, pot, potm, potx, pps, ppsm, ppsx, ppt, pptm, pptx, presentation, rtf, spreadsheet, sxc, txt, vdw, vdx, visio, vsd, vsdm, vsdx, vss, vssm, vssx, vst, vstm, vstx, vsx, vtx, word, worksheet, xlam, xls, xlsb, xlsm, xlsx, xlt, xltm, xltx]
  
outputPath: "watermark\\{product}\\{operation}\\{watermarktype}\\{fileformat}.{lang}.md"
