inherits: ..\\languages-family-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [search]
- alias:  fileformat
  values: [excel, word, powerpoint]

generationRules:
  include:
  - fileformat[excel, word, powerpoint]
  
outputPath: "watermark\\{product}\\find\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
