inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [nodejs-java]
- alias:  operation
  values: [search]
- alias:  url
  values: [get]
- alias:  fileformat
  values: [doc, docx, pdf, ppt, pptx, rtf, xls, xlsx]

generationRules:
  include:
  - fileformat[doc, docx, pdf, ppt, pptx, rtf, xls, xlsx]
  
outputPath: "watermark\\{product}\\{url}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
